import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Metadata } from "next";
import QueryProvider from "@/src/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Noonchi.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="min-h-screen w-full">
        <QueryProvider>
          <div className="flex flex-col h-full">
            <main className="flex-grow w-full ">{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
