import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Metadata } from "next";

import ModalRender from "@/components/modal/ModalRender";
import { ClientProvider, QueryProvider } from "@/providers";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Noonchi.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head></head>
      <body className="min-h-screen w-full">
        <SessionProvider>
          <QueryProvider>
            <ClientProvider>
              <div className="w-full min-h-screen md:flex md:justify-center">
                <div className="w-full md:max-w-93.75 md:shadow-xl bg-gradient-primary">
                  {children}
                </div>
              </div>
              <ModalRender />
            </ClientProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
